# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Loop for hitandrun
#' 
#' Runs the hitandrun algorithm in a loop
#' @name hnr_loop
#' @param y_s: starting point
#' @param Z_s: null-space matrix
#' @param n_s: number of outputs
#' @param skiplength_s: number to skip
#' @param discard_s: burninlength
#' 
#' @export
NULL

hnr_loop <- function(y_s, Z_s, n_s, skiplength_s, discard_s) {
    .Call('kmatching_hnr_loop', PACKAGE = 'kmatching', y_s, Z_s, n_s, skiplength_s, discard_s)
}

