# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hnr_loop <- function(y_s, Z_s, n_s, skiplength_s, discard_s) {
    .Call('kmatching_hnr_loop', PACKAGE = 'kmatching', y_s, Z_s, n_s, skiplength_s, discard_s)
}

